
// Implementing some member_functions which depend on TNumericConstant

o_namespace_begin(phantom)

o_define_template_signature_parameter_phantom_element_impl(boolean)
o_define_template_signature_parameter_phantom_element_impl(uchar)
o_define_template_signature_parameter_phantom_element_impl(schar)
o_define_template_signature_parameter_phantom_element_impl(ushort)
o_define_template_signature_parameter_phantom_element_impl(sshort)
o_define_template_signature_parameter_phantom_element_impl(uint)
o_define_template_signature_parameter_phantom_element_impl(sint)
o_define_template_signature_parameter_phantom_element_impl(size_t)
o_define_template_signature_parameter_phantom_element_impl(ulong)
o_define_template_signature_parameter_phantom_element_impl(slong)
o_define_template_signature_parameter_phantom_element_impl(longlong)
o_define_template_signature_parameter_phantom_element_impl(ulonglong)

o_define_template_signature_parameter_element_impl(bool)
o_define_template_signature_parameter_element_impl(char)
o_define_template_signature_parameter_element_impl(short)
o_define_template_signature_parameter_element_impl(int)
o_define_template_signature_parameter_element_impl(long)
o_define_template_signature_parameter_element_impl(size_t)
o_define_template_signature_parameter_element_impl(uchar)
o_define_template_signature_parameter_element_impl(schar)
o_define_template_signature_parameter_element_impl(ushort)
o_define_template_signature_parameter_element_impl(sshort)
o_define_template_signature_parameter_element_impl(uint)
o_define_template_signature_parameter_element_impl(sint)
o_define_template_signature_parameter_element_impl(ulong)
o_define_template_signature_parameter_element_impl(slong)
o_define_template_signature_parameter_element_impl(longlong)
o_define_template_signature_parameter_element_impl(ulonglong)
o_define_template_signature_parameter_element_impl(unsigned)

template<ulonglong value>
phantom::reflection::LanguageElement*
    reflection::detail::template_signature_parameter_enum<value>::object()
{
    return o_dynamic_proxy_new(phantom::reflection::native::TNumericConstant<ulonglong>)("", value, o_native);
}

o_namespace_end(phantom)