#ifndef o_phantom_fwd_h__
#define o_phantom_fwd_h__



o_fwd(class, phantom, Phantom)
o_fwd(class, phantom, Object)

o_fwd(struct, phantom, reflection, CodePosition)
o_fwd(class, phantom, reflection, CodeLocation)
o_fwd(class, phantom, reflection, SourceFile)
o_fwd(class, phantom, reflection, Signature)
o_fwd(class, phantom, reflection, Subroutine)
o_fwd(class, phantom, reflection, Block)
o_fwd(class, phantom, reflection, LocalVariable)
o_fwd(class, phantom, reflection, Function)
o_fwd(class, phantom, reflection, Constant)
o_fwd(class, phantom, reflection, Variable)
o_fwd(class, phantom, reflection, StaticVariable)
o_fwd(class, phantom, reflection, Member)
o_fwd(class, phantom, reflection, Method)
o_fwd(class, phantom, reflection, StaticMethod)
o_fwd(class, phantom, reflection, Constructor)
o_fwd(class, phantom, reflection, InstanceMethod)
o_fwd(class, phantom, reflection, Signal)
o_fwd(class, phantom, reflection, Attribute)
o_fwd(class, phantom, reflection, InstanceAttribute)
o_fwd(class, phantom, reflection, StaticAttribute)
o_fwd(class, phantom, reflection, Accessor)
o_fwd(class, phantom, reflection, Property)
o_fwd(class, phantom, reflection, Type)
o_fwd(class, phantom, reflection, PrimitiveType)
o_fwd(class, phantom, reflection, PointerType)
o_fwd(class, phantom, reflection, DataPointerType)
o_fwd(class, phantom, reflection, ConstDataPointerType)
o_fwd(class, phantom, reflection, ReferenceType)
o_fwd(class, phantom, reflection, ConstReferenceType)
o_fwd(class, phantom, reflection, ArrayType)
o_fwd(class, phantom, reflection, Class)
o_fwd(class, phantom, reflection, ClassType)
o_fwd(class, phantom, reflection, ContainerClass)
o_fwd(class, phantom, reflection, SequentialContainerClass)
o_fwd(class, phantom, reflection, MapContainerClass)
o_fwd(class, phantom, reflection, SetContainerClass)
o_fwd(class, phantom, reflection, IteratorConstant)
o_fwd(class, phantom, reflection, IteratorVariable)
o_fwd(class, phantom, reflection, PODUnion)
o_fwd(class, phantom, reflection, PODStruct)
o_fwd(class, phantom, reflection, Union)
o_fwd(class, phantom, reflection, LanguageElement)
o_fwd(class, phantom, reflection, TemplateElement)
o_fwd(class, phantom, reflection, VirtualMethodTable)
o_fwd(class, phantom, reflection, Namespace)
o_fwd(class, phantom, reflection, TemplateSpecialization)

o_fwd(class, phantom, state, StateMachine)
o_fwd(class, phantom, state, StateMachineElement)
o_fwd(class, phantom, state, State)
o_fwd(class, phantom, state, Track)
o_fwd(class, phantom, state, Event)
o_fwd(class, phantom, state, Reaction)
o_fwdT(class, phantom, state, native, (typename), TNativeState)
o_fwdT(class, phantom, state, native, (typename, typename, typename, typename), TNativeTransition)
o_fwdT(class, phantom, state, native, (typename), TNativeTrack)
o_fwdT(class, phantom, state, native, (typename), TNativeStateMachine)
o_fwdT(class, phantom, state, native, (typename,bool), TNativeStateMachineHelper)

o_fwd(class, phantom, serialization, Node)
o_fwd(class, phantom, serialization, DataBase)
o_fwd(class, phantom, serialization, DataStateBase)
o_fwd(class, phantom, serialization, Bundle)
o_fwd(class, phantom, serialization, BundleNode)
o_fwd(class, phantom, serialization, BundleDataBase)
    
o_fwdT(class, phantom, reflection, native, (typename,typename), TNativeInstanceMethod0 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename), TNativeInstanceMethod1 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename), TNativeInstanceMethod2 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename), TNativeInstanceMethod3 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename), TNativeInstanceMethod4 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename), TNativeInstanceMethod5 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename), TNativeInstanceMethod6 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename,typename), TNativeInstanceMethod7 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename,typename,typename), TNativeInstanceMethod8 )

o_fwdT(class, phantom, reflection, native, (typename,typename), TNativeInstanceMethodConst0 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename), TNativeInstanceMethodConst1 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename), TNativeInstanceMethodConst2 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename), TNativeInstanceMethodConst3 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename), TNativeInstanceMethodConst4 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename), TNativeInstanceMethodConst5 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename), TNativeInstanceMethodConst6 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename,typename), TNativeInstanceMethodConst7 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename,typename,typename), TNativeInstanceMethodConst8 )

o_fwdT(class, phantom, reflection, native, (typename,typename), TNativeInterfaceMethod0 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename), TNativeInterfaceMethod1 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename), TNativeInterfaceMethod2 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename), TNativeInterfaceMethod3 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename), TNativeInterfaceMethod4 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename), TNativeInterfaceMethod5 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename), TNativeInterfaceMethod6 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename,typename), TNativeInterfaceMethod7 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename,typename,typename), TNativeInterfaceMethod8 )

o_fwdT(class, phantom, reflection, native, (typename,typename), TNativeInterfaceMethodConst0 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename), TNativeInterfaceMethodConst1 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename), TNativeInterfaceMethodConst2 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename), TNativeInterfaceMethodConst3 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename), TNativeInterfaceMethodConst4 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename), TNativeInterfaceMethodConst5 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename), TNativeInterfaceMethodConst6 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename,typename), TNativeInterfaceMethodConst7 )
o_fwdT(class, phantom, reflection, native, (typename,typename,typename,typename,typename,typename,typename,typename,typename,typename), TNativeInterfaceMethodConst8 )

o_fwdT(class, phantom, reflection, native, (typename), TConstant)

o_fwdT(class, phantom, reflection, native, (typename), TType)
o_fwdT(class, phantom, reflection, native, (typename), TType_)
o_fwdT(class, phantom, reflection, native, (typename,int), TTypeHelper)
o_fwdT(class, phantom, reflection, native, (typename), TConstType)
o_fwdT(class, phantom, reflection, native, (typename, typename), TNativeSignal)
o_fwdT(class, phantom, reflection, native, (typename, typename), TNativeInstanceMethod)
o_fwdT(class, phantom, reflection, native, (typename, typename), TNativeInstanceMethodConst)
o_fwdT(class, phantom, reflection, native, (typename, typename), TNativeInterfaceMethod)
o_fwdT(class, phantom, reflection, native, (typename, typename), TNativeInterfaceMethodConst)
o_fwdT(class, phantom, reflection, native, (typename, typename), TNativeStaticMethod)
o_fwdT(class, phantom, reflection, native, (typename, typename), TNativeInstanceAttribute)
o_fwdT(class, phantom, reflection, native, (typename, typename), TNativeStaticAttribute)

o_fwdT(class, phantom, reflection, native, (typename, uint, typename), TNativeAttributeProvider)

#ifdef o_NO_FUNCTION_STYLE_TEMPLATE_SIGNATURE
o_fwdT(class, phantom, reflection, native, (typename, uint, typename, typename, typename), TNativeMethodProvider)
o_fwdT(class, phantom, reflection, native, (typename, uint, typename, typename, typename), TNativeInterfaceMethodProvider)
o_fwdT(class, phantom, reflection, native, (typename, typename, typename), TNativeSignatureProvider)
#else
o_fwdT(class, phantom, reflection, native, (typename, uint, typename), TNativeMethodProvider)
o_fwdT(class, phantom, reflection, native, (typename, uint, typename), TNativeInterfaceMethodProvider)
o_fwdT(class, phantom, reflection, native, (int, typename), TNativeSignatureProvider)
#endif

o_fwdT(class, phantom, serialization, native, (typename), TBundle)
o_fwdT(class, phantom, state, native, (typename), root_statechart)

#endif // o_phantom_fwd_h__
