


o_declareN(class, (phantom), Phantom)
o_declareN(class, (phantom), Module)
o_declareN(class, (phantom), Iterator)
o_declareN(class, (phantom, reflection), Range)
o_declareN(class, (phantom, reflection), SourceFile)
o_declareN(class, (phantom, reflection), Signature)
o_declareN(class, (phantom, reflection), Subroutine)
o_declareN(class, (phantom, reflection), Function)
o_declareN(class, (phantom, reflection), Variable)
o_declareN(class, (phantom, reflection), IteratorConstant)
o_declareN(class, (phantom, reflection), IteratorVariable)
o_declareN(class, (phantom, reflection), StaticVariable)
o_declareN(class, (phantom, reflection), Member)
o_declareN(class, (phantom, reflection), MemberFunction)
o_declareN(class, (phantom, reflection), StaticMemberFunction)
o_declareN(class, (phantom, reflection), Constructor)
o_declareN(class, (phantom, reflection), InstanceMemberFunction)
o_declareN(class, (phantom, reflection), Signal)
o_declareN(class, (phantom, reflection), DataMember)
o_declareN(class, (phantom, reflection), InstanceDataMember)
o_declareN(class, (phantom, reflection), StaticDataMember)
o_declareN(class, (phantom, reflection), Property)
o_declareN(class, (phantom, reflection), Collection)
o_declareN(class, (phantom, reflection), ValueMember)
o_declareN(class, (phantom, reflection), ValueMemberBinding)
o_declareN(class, (phantom, reflection), Type)
o_declareN(class, (phantom, reflection), PrimitiveType)
o_declareN(class, (phantom, reflection), PointerType)
o_declareN(class, (phantom, reflection), DataPointerType)
o_declareN(class, (phantom, reflection), ConstDataPointerType)
o_declareN(class, (phantom, reflection), ReferenceType)
o_declareN(class, (phantom, reflection), ConstReferenceType)
o_declareN(class, (phantom, reflection), ArrayType)
o_declareN(class, (phantom, reflection), Class)
o_declareN(class, (phantom, reflection), ClassType)
o_declareN(class, (phantom, reflection), PODUnion)
o_declareN(class, (phantom, reflection), PODStruct)
o_declareN(class, (phantom, reflection), Union)
o_declareN(class, (phantom, reflection), Enum)
o_declareN(class, (phantom, reflection), LanguageElement)
o_declareN(class, (phantom, reflection), TemplateElement)
o_declareN(class, (phantom, reflection), Constant)
o_declareN(class, (phantom, reflection), VirtualMemberFunctionTable)
o_declareN(class, (phantom, reflection), Namespace)
o_declareN(class, (phantom, reflection), TemplateSpecialization)
o_declareN(class, (phantom, reflection), ContainerClass)
o_declareN(class, (phantom, reflection), SequentialContainerClass)
o_declareN(class, (phantom, reflection), SetContainerClass)
o_declareN(class, (phantom, reflection), MapContainerClass)



o_declareN(class, (phantom, state), StateMachine)
o_declareN(class, (phantom, state), StateMachineElement)
o_declareN(class, (phantom, state), State)
o_declareN(class, (phantom, state), Track)
o_declareN(class, (phantom, state), Event)
o_declareN(class, (phantom, state), Reaction)
o_declareNT(class, (phantom, state, native), (typename), (t_Ty), TNativeState)
o_declareNT(class, (phantom, state, native), (typename, typename, typename, typename), (t_Ty, t_Src, t_Evt, t_Tgt),TNativeTransition)
o_declareNT(class, (phantom, state, native), (typename), (t_Ty), TNativeTrack)
o_declareNT(class, (phantom, state, native), (typename), (t_Ty), TNativeStateMachine)



o_declareN(class, (phantom, serialization), Node)
o_declareN(class, (phantom, serialization), DefaultNode)
o_declareN(class, (phantom, serialization), DataBase)
o_declareN(class, (phantom, serialization), DataStateBase)


