


o_declareN(class, (phantom), Phantom)
o_declareN(class, (phantom), Iterator)
o_declareN(class, (phantom, reflection), Module)
o_declareN(class, (phantom, reflection), Range)
o_declareN(class, (phantom, reflection), Source)
o_declareN(class, (phantom, reflection), Signature)
o_declareN(class, (phantom, reflection), Subroutine)
o_declareN(class, (phantom, reflection), Function)
o_declareN(class, (phantom), ConstIterator)
o_declareN(class, (phantom), Iterator)
o_declareN(class, (phantom, reflection), Variable)
o_declareN(class, (phantom, reflection), Member)
o_declareN(class, (phantom, reflection), Constructor)
o_declareN(class, (phantom, reflection), MemberFunction)
o_declareN(class, (phantom, reflection), Signal)
o_declareN(class, (phantom, reflection), DataMember)
o_declareN(class, (phantom, reflection), AnonymousSection)
o_declareN(class, (phantom, reflection), AnonymousStruct)
o_declareN(class, (phantom, reflection), AnonymousUnion)
o_declareN(class, (phantom, reflection), Property)
o_declareN(class, (phantom, reflection), ValueMember)
o_declareN(class, (phantom, reflection), DataMemberBinding)
o_declareN(class, (phantom, reflection), Type)
o_declareN(class, (phantom, reflection), PrimitiveType)
o_declareN(class, (phantom, reflection), PointerType)
o_declareN(class, (phantom, reflection), DataPointerType)
o_declareN(class, (phantom, reflection), LValueReferenceType)
o_declareN(class, (phantom, reflection), ArrayType)
o_declareN(class, (phantom, reflection), Class)
o_declareN(class, (phantom, reflection), ClassType)
o_declareN(class, (phantom, reflection), Structure)
o_declareN(class, (phantom, reflection), Union)
o_declareN(class, (phantom, reflection), Enum)
o_declareN(class, (phantom, reflection), LanguageElement)
o_declareN(class, (phantom, reflection), LanguageElement)
o_declareN(class, (phantom, reflection), Constant)
o_declareN(class, (phantom, reflection), NumericConstant)
o_declareN(class, (phantom, reflection), VirtualMemberFunctionTable)
o_declareN(class, (phantom, reflection), Namespace)
o_declareN(class, (phantom, reflection), TemplateSpecialization)
o_declareN(class, (phantom, reflection), ContainerClass)
o_declareN(class, (phantom, reflection), SequentialContainerClass)
o_declareN(class, (phantom, reflection), SetContainerClass)
o_declareN(class, (phantom, reflection), MapContainerClass)



o_declareN(class, (phantom, reflection), StateMachine)
o_declareN(class, (phantom, reflection), StateMachineElement)
o_declareN(class, (phantom, reflection), State)
o_declareN(class, (phantom, reflection), Track)
o_declareN(class, (phantom, reflection), Event)
o_declareN(class, (phantom, reflection), Reaction)
o_declareNT(class, (phantom, reflection, native), (typename), (t_Ty), TNativeState)
o_declareNT(class, (phantom, reflection, native), (typename, typename, typename, typename), (t_Ty, t_Src, t_Evt, t_Tgt),TNativeTransition)
o_declareNT(class, (phantom, reflection, native), (typename), (t_Ty), TNativeTrack)
o_declareNT(class, (phantom, reflection, native), (typename), (t_Ty), TNativeStateMachine)



o_declareN(class, (phantom, serialization), Node)
o_declareN(class, (phantom, serialization), DefaultNode)
o_declareN(class, (phantom, serialization), DataBase)
o_declareN(class, (phantom, serialization), DataStateBase)
