
// Implementing some member_functions which depend on TConstant

o_namespace_begin(phantom)

o_define_template_signature_parameter_counter_phantom_element_impl(boolean)
o_define_template_signature_parameter_counter_phantom_element_impl(uchar)
o_define_template_signature_parameter_counter_phantom_element_impl(schar)
o_define_template_signature_parameter_counter_phantom_element_impl(ushort)
o_define_template_signature_parameter_counter_phantom_element_impl(sshort)
o_define_template_signature_parameter_counter_phantom_element_impl(uint)
o_define_template_signature_parameter_counter_phantom_element_impl(sint)
o_define_template_signature_parameter_counter_phantom_element_impl(size_t)
o_define_template_signature_parameter_counter_phantom_element_impl(ulong)
o_define_template_signature_parameter_counter_phantom_element_impl(slong)
o_define_template_signature_parameter_counter_phantom_element_impl(longlong)
o_define_template_signature_parameter_counter_phantom_element_impl(ulonglong)

o_define_template_signature_parameter_counter_element_impl(bool)
o_define_template_signature_parameter_counter_element_impl(char)
o_define_template_signature_parameter_counter_element_impl(short)
o_define_template_signature_parameter_counter_element_impl(int)
o_define_template_signature_parameter_counter_element_impl(long)
o_define_template_signature_parameter_counter_element_impl(size_t)
o_define_template_signature_parameter_counter_element_impl(uchar)
o_define_template_signature_parameter_counter_element_impl(schar)
o_define_template_signature_parameter_counter_element_impl(ushort)
o_define_template_signature_parameter_counter_element_impl(sshort)
o_define_template_signature_parameter_counter_element_impl(uint)
o_define_template_signature_parameter_counter_element_impl(sint)
o_define_template_signature_parameter_counter_element_impl(ulong)
o_define_template_signature_parameter_counter_element_impl(slong)
o_define_template_signature_parameter_counter_element_impl(longlong)
o_define_template_signature_parameter_counter_element_impl(ulonglong)
o_define_template_signature_parameter_counter_element_impl(unsigned)

template<ulonglong value, int t_counter>
phantom::reflection::TemplateElement*
    reflection::detail::template_signature_parameter_counter_enum<value, t_counter>::object()
{
    return o_dynamic_proxy_new(phantom::reflection::Constant, phantom::reflection::Constant::metaType, phantom::reflection::native::TConstant<ulonglong>)("", value);
}

o_namespace_end(phantom)