/* TODO LICENCE HERE */
/*

template<typename _T0, template<typename _T0> class _TTy>
    o_forceinline static phantom::reflection::Type*    contentTypeOf(_TTy<_T0>* p)
{
    return _TTy<_T0>::Reflect(); // Default for template is to call the Reflect() function generated by reflection 
}

template<typename _T0
    , typename _T1
    , template<typename _T0
            , typename _T1> class _TTy>
    o_forceinline static phantom::reflection::Type*    contentTypeOf(_TTy<_T0,_T1>* p)
{
    return _TTy<_T0,_T1>::Reflect(); // Default for template is to call the Reflect() function generated by reflection 
}

template<typename _T0
    , typename _T1
    , typename _T2
    , template<typename _T0
            , typename _T1
            , typename _T2> class _TTy>
    o_forceinline static phantom::reflection::Type*    contentTypeOf(_TTy<_T0,_T1,_T2>* p)
{
    return _TTy<_T0,_T1,_T2>::Reflect(); // Default for template is to call the Reflect() function generated by reflection 
}

template<typename _T0
    , typename _T1
    , typename _T2
    , typename _T3
    , template<typename _T0
            , typename _T1
            , typename _T2
            , typename _T3> class _TTy>
    o_forceinline static phantom::reflection::Type*    contentTypeOf(_TTy<_T0,_T1,_T2,_T3>* p)
{
    return _TTy<_T0,_T1,_T2,_T3>::Reflect(); // Default for template is to call the Reflect() function generated by reflection 
}

template<typename _T0
    , typename _T1
    , typename _T2
    , typename _T3
    , typename _T4
    , template<typename _T0
            , typename _T1
            , typename _T2
            , typename _T3
            , typename _T4> class _TTy>
    o_forceinline static phantom::reflection::Type*    contentTypeOf(_TTy<_T0,_T1,_T2,_T3,_T4>* p)
{
    return _TTy<_T0,_T1,_T2,_T3,_T4>::Reflect(); // Default for template is to call the Reflect() function generated by reflection 
}

template<typename _T0
    , typename _T1
    , typename _T2
    , typename _T3
    , typename _T4
    , typename _T5
    , template<typename _T0
            , typename _T1
            , typename _T2
            , typename _T3
            , typename _T4
            , typename _T5> class _TTy>
    o_forceinline static phantom::reflection::Type*    contentTypeOf(_TTy<_T0,_T1,_T2,_T3,_T4,_T5>* p)
{
    return _TTy<_T0,_T1,_T2,_T3,_T4,_T5>::Reflect(); // Default for template is to call the Reflect() function generated by reflection 
}

template<typename _T0
    , typename _T1
    , typename _T2
    , typename _T3
    , typename _T4
    , typename _T5
    , typename _T6
    , template<typename _T0
            , typename _T1
            , typename _T2
            , typename _T3
            , typename _T4
            , typename _T5
            , typename _T6> class _TTy>
    o_forceinline static phantom::reflection::Type*    contentTypeOf(_TTy<_T0,_T1,_T2,_T3,_T4,_T5,_T6>* p)
{
    return _TTy<_T0,_T1,_T2,_T3,_T4,_T5,_T6>::Reflect(); // Default for template is to call the Reflect() function generated by reflection 
}

template<typename _T0
    , typename _T1
    , typename _T2
    , typename _T3
    , typename _T4
    , typename _T5
    , typename _T6
    , typename _T7
    , template<typename _T0
            , typename _T1
            , typename _T2
            , typename _T3
            , typename _T4
            , typename _T5
            , typename _T6
            , typename _T7> class _TTy>
    o_forceinline static phantom::reflection::Type*    contentTypeOf(_TTy<_T0,_T1,_T2,_T3,_T4,_T5,_T6,_T7>* p)
{
    return _TTy<_T0,_T1,_T2,_T3,_T4,_T5,_T6,_T7>::Reflect(); // Default for template is to call the Reflect() function generated by reflection 
}

template<typename _T0
    , typename _T1
    , typename _T2
    , typename _T3
    , typename _T4
    , typename _T5
    , typename _T6
    , typename _T7
    , typename _T8
    , template<typename _T0
            , typename _T1
            , typename _T2
            , typename _T3
            , typename _T4
            , typename _T5
            , typename _T6
            , typename _T7
            , typename _T8
                    > class _TTy>
    o_forceinline static phantom::reflection::Type*    contentTypeOf(_TTy<_T0,_T1,_T2,_T3,_T4,_T5,_T6,_T7,_T8>* p)
{
    return _TTy<_T0,_T1,_T2,_T3,_T4,_T5,_T6,_T7,_T8>::Reflect(); // Default for template is to call the Reflect() function generated by reflection 
}

template<typename _T0
    , typename _T1
    , typename _T2
    , typename _T3
    , typename _T4
    , typename _T5
    , typename _T6
    , typename _T7
    , typename _T8
    , typename _T9
    , template<typename _T0
            , typename _T1
            , typename _T2
            , typename _T3
            , typename _T4
            , typename _T5
            , typename _T6
            , typename _T7
            , typename _T8
            , typename _T9> class _TTy>
    o_forceinline static phantom::reflection::Type*    contentTypeOf(_TTy<_T0,_T1,_T2,_T3,_T4,_T5,_T6,_T7,_T8,_T9>* p)
{
    return _TTy<_T0,_T1,_T2,_T3,_T4,_T5,_T6,_T7,_T8,_T9>::Reflect(); // Default for template is to call the Reflect() function generated by reflection 
}*/